name: Lab5 Pipeline (unittest)

on:
  push:

jobs:
  unit-test: 
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3 

      - name: Set up Python 
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Run unit tests
        run: |
          python -m unittest discover 
          echo Retry
          python -m unittest discover 
